### ISSUE TITLE
[BLOG] Endereço dos botões do blog:

### ISSUE THREAD

**Issue by BrunoSavieto** [heliorneto/Rope-up#16]
"veja todos os assuntos"
como não temos muitos assuntos acho que pode tirar esse botão por agora

assine a newsletter 
"veja todos os assuntos" acho que pode trocar o que ta escrito no botao por "receber conteudos exclusivos"
ai abre um popup para a pessoa colocar o email dela (bem simples - so nome e email)

**Comment by PedroPires20** [comment]
Revisado após mudança do backend (Botão voltou) e implementado na última versão (newsletter).
