### ISSUE TITLE
[BLOG] Formatação do escrito dentro das caixinhas no blog

### ISSUE THREAD

**Issue by BrunoSavieto** [heliorneto/Rope-up#19]
colocar faixa de alguma cor (pode ser com alta transparencia) (pequena) atras dos textos para previnir que a cor da imagem atrapalhe a leitura do texto

o texto deve ficar com um pading da esquerda maior 

tamanho e cor ok!

**Comment by PedroPires20** [comment]
Foi decidido manter como está!
