### ISSUE TITLE
Tamanho da última imagem do blog

### ISSUE THREAD

**Issue by heliorneto** [heliorneto/Rope-up#3]
A última imagem do blog está com uma altura muito grande e esticada para o iphone 6s(meu celular no heroku). Deve ser alguma configuração de altura, tentar modificar a altura para uma unidade de medida que seja proporcional a tela. Caso não dê certo, fazer um media pra as configurações desse dispositivo.

**Comment by PedroPires20** [comment]
Testei no meu celular (iPhone 7 plus) e no simulador e o problema não ocorreu. É necessária uma nova testagem apenas para validação.
